dist: bionic

language: cpp

before_install:
  # The Coverity Scan certificate-chain is missing an intermediate certificate
  - >
    sudo curl -s -L https://entrust.com/root-certificates/entrust_l1k.cer -o
    /usr/local/share/ca-certificates/entrust_l1k.crt
  - sudo update-ca-certificates
  - >
    echo -n | openssl s_client -connect scan.coverity.com:443 |
    sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' |
    sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - sudo iptables -F

addons:
  coverity_scan:

    # GitHub project metadata
    # ** specific to your project **
    project:
      name: MKL-DNN
      version: 1.0
      description: My Project

    # Where email notification of build analysis results will be sent
    notification_email: nikolay.a.petrov@intel.com

    # Commands to prepare for build_command
    # ** likely specific to your build **
    build_command_prepend: mkdir -p build && cd build && cmake $CMAKE_OPTIONS .. 

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    build_command: make -j2

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan
