# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: cd scripts && call prepare_mkl.bat && cd ..
  - script: mkdir build & cd build && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -G "Visual Studio 16 2019" -A x64 ..
  - task: MSBuild@1
    inputs:
      solution: 'build\Intel(R) MKL-DNN.sln'
      msbuildArchitecture: 'x64'
      configuration: 'Release'
      clean: true
  - script: |
      cd build && ctest
    displayName: 'ctest'