version: 2
jobs:
  build:
    docker:
      - image: gcc:8.3
    steps:
      - checkout
      - run: sudo apt install -y cmake
      - run: mkdir -p build && cd build && cmake $CMAKE_OPTIONS ..
      - run: cd build && make   
