version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: sudo apt install -y cmake
      - run: mkdir -p build && cd build && cmake $CMAKE_OPTIONS ..
      - run: cd build && make   
